#!/usr/bin/env bash

http --pretty colors localhost:7100/stream_edits <<'EOF'
{
  "outline": "```lua/ask-openai/prediction/tests/calc/calc.lua\nclass BigThing\nclass HugeThing\nclass MegaThing\nfunction M.add\nfunction M.sub\nfunction M.mul\nfunction M.div\n```",
  "input_events": "User edited \"lua/ask-openai/prediction/tests/calc/calc.lua\":\n```diff\n@@ -1,0 +1,40 @@\n+local BigThing = {}\n+\n+function BigThing.new(name)\n+    return setmetatable({\n+        name = name,\n+        data = {},\n+    }, { __index = BigThing })\n+end\n+\n+function BigThing:reset()\n+    self.data = {}\n+end\n+\n+function BigThing:add_entry(key, value)\n+    self.data[key] = value\n+end\n+\n+function BigThing:summary()\n+    return string.format(\"BigThing[%s] has %d items\", self.name, #self.data)\n+end\n+\n+local HugeThing = {}\n+\n+function HugeThing.new(id)\n+    return setmetatable({\n+        id = id,\n+        events = {},\n+    }, { __index = HugeThing })\n+end\n+\n+function HugeThing:log(event)\n+    table.insert(self.events, event)\n+end\n+\n+function HugeThing:count()\n+    return #self.events\n+end\n+\n+function HugeThing:report()\n+    return table.concat(self.events, \", \")\n+end\n\n```diff\n@@ -41,0 +41,22 @@\n+local MegaThing = {}\n+\n+function MegaThing.new()\n+    return setmetatable({\n+        status = \"idle\",\n+        counter = 0,\n+    }, { __index = MegaThing })\n+end\n+\n+function MegaThing:start()\n+    self.status = \"running\"\n+end\n+\n+function MegaThing:stop()\n+    self.status = \"stopped\"\n+end\n+\n+function MegaThing:tick()\n+    self.counter = self.counter + 1\n+end\n+\n+function MegaThing:state()\n+    return self.status, self.counter\n+end\n\n```diff\n@@ -65,4 +87,9 @@\n+\n+function M.div(a, b)\n+    if b == 0 then\n+        return nil, \"divide by zero\"\n+    end\n+    return a / b\n+end\n\n return M\n```",
  "input_excerpt": "```ask-openai.nvim/lua/ask-openai/prediction/tests/calc/calc.lua\n<|start_of_file|>\n<|editable_region_start|>\nlocal BigThing = {}\n\nfunction BigThing.new(name)\n    return setmetatable({\n        name = name,\n        data = {},\n    }, { __index = BigThing })\nend\n\nfunction BigThing:reset()\n    self.data = {}\nend\n\nfunction BigThing:add_entry(key, value)\n    self.data[key] = value\nend\n\nfunction BigThing:summary()\n    return string.format(\"BigThing[%s] has %d items\", self.name, #self.data)\nend\n\n\nlocal HugeThing = {}\n\nfunction HugeThing.new(id)\n    return setmetatable({\n        id = id,\n        events = {},\n    }, { __index = HugeThing })\nend\n\nfunction HugeThing:log(event)\n    table.insert(self.events, event)\nend\n\nfunction HugeThing:count()\n    return #self.events\nend\n\nfunction HugeThing:report()\n    return table.concat(self.events, \", \")\nend\n\n\nlocal MegaThing = {}\n\nfunction MegaThing.new()\n    return setmetatable({\n        status = \"idle\",\n        counter = 0,\n    }, { __index = MegaThing })\nend\n\nfunction MegaThing:start()\n    self.status = \"running\"\nend\n\nfunction MegaThing:stop()\n    self.status = \"stopped\"\nend\n\nfunction MegaThing:tick()\n    self.counter = self.counter + 1\nend\n\nfunction MegaThing:state()\n    return self.status, self.counter\nend\n\n\nlocal M = {}\n\nfunction M.add(a, b)\n    return a + b\nend\n\nfunction M.sub(a, b)\n    return a - b\nend\n\nfunction M.mul(a, b)\n    return a * b\nend\n\nfunction M.div(a, b)\n    if b == 0 then\n        return nil, \"divide by zero\"\n    end\n    return a / b\nend\n\n<|user_cursor_is_here|>\nreturn M\n<|editable_region_end|>\n```",
  "speculated_output": "<|editable_region_start|>\n<-- all content from input_excerpt exactly as-is -->\n<|editable_region_end|>",
  "can_collect_data": false,
  "diagnostic_groups": [],
  "include_finish_reason": true
}
EOF
